language: java
install: true
sudo: false # faster builds

jdk:
  - oraclejdk8

script:
  - ./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - export CODECOV_TOKEN="8dc5b9f1-d6fd-43d5-a937-b53600c458b7"
  - bash <(curl -s https://codecov.io/bash)