install: gradle wrapper --gradle-version 4.2
language: java

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)